
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 18/05/2017 09:50:06
//----------------------------------------------------

namespace TypeCobol.DocumentModel.Dom.Parser
 {

using TypeCobol.DocumentModel.Dom;
using TypeCobol.Compiler.CodeElements;
using System.Collections.Generic;
using System.Collections;
using System;
using TUVienna.CS_CUP.Runtime;

/** C# CUP v0.1 generated parser.
  * @version 18/05/2017 09:50:06
  */
public class ProgramParser : TUVienna.CS_CUP.Runtime.lr_parser {

  /** Default constructor. */
  public ProgramParser():base() {;}

  /** Constructor which sets the default scanner. */
  public ProgramParser(TUVienna.CS_CUP.Runtime.Scanner s): base(s) {;}

  /** Production table. */
  protected static readonly short[][] _production_table = 
    unpackFromStrings(new string[] {
    "/000/046/000/002/003/003/000/002/002/004/000/002/004" +
    "/005/000/002/005/004/000/002/006/002/000/002/006/003" +
    "/000/002/010/002/000/002/010/003/000/002/011/005/000" +
    "/002/012/002/000/002/012/003/000/002/013/003/000/002" +
    "/013/004/000/002/016/003/000/002/016/004/000/002/017" +
    "/003/000/002/017/003/000/002/017/003/000/002/017/003" +
    "/000/002/014/002/000/002/014/003/000/002/015/005/000" +
    "/002/020/002/000/002/020/003/000/002/021/004/000/002" +
    "/022/002/000/002/022/003/000/002/023/003/000/002/023" +
    "/004/000/002/024/002/000/002/024/003/000/002/025/004" +
    "/000/002/026/002/000/002/026/004/000/002/027/003/000" +
    "/002/027/004/000/002/007/002/000/002/007/003" });

  /** Access to production table. */
  public override short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static readonly short[][] _action_table = 
    unpackFromStrings(new string[] {
    "/000/051/000/004/004/005/001/002/000/004/002/053/001" +
    "/002/000/012/002/ufffd/005/ufffd/016/ufffd/173/051/001/002" +
    "/000/010/002/ufffb/005/ufffb/016/010/001/002/000/004/002" +
    "/001/001/002/000/012/002/ufff8/005/ufff8/024/015/025/ufff8" +
    "/001/002/000/006/002/uffdd/005/014/001/002/000/006/002" +
    "/ufffa/005/ufffa/001/002/000/004/002/uffff/001/002/000/004" +
    "/002/uffdc/001/002/000/020/002/ufff6/005/ufff6/025/ufff6/045" +
    "/042/046/045/047/043/050/044/001/002/000/010/002/ufff7" +
    "/005/ufff7/025/ufff7/001/002/000/010/002/uffee/005/uffee/025" +
    "/021/001/002/000/006/002/ufff9/005/ufff9/001/002/000/012" +
    "/002/uffeb/005/uffeb/033/023/034/uffeb/001/002/000/006/002" +
    "/uffed/005/uffed/001/002/000/012/002/uffe8/005/uffe8/034/uffe8" +
    "/043/040/001/002/000/010/002/uffea/005/uffea/034/uffea/001" +
    "/002/000/010/002/uffe4/005/uffe4/034/026/001/002/000/010" +
    "/002/uffe1/005/uffe1/044/031/001/002/000/006/002/uffe3/005" +
    "/uffe3/001/002/000/006/002/uffec/005/uffec/001/002/000/006" +
    "/035/uffdf/044/uffdf/001/002/000/006/002/uffe2/005/uffe2/001" +
    "/002/000/006/035/035/044/034/001/002/000/006/035/uffde" +
    "/044/uffde/001/002/000/006/002/uffe0/005/uffe0/001/002/000" +
    "/010/002/uffe9/005/uffe9/034/uffe9/001/002/000/012/002/uffe7" +
    "/005/uffe7/034/uffe7/043/041/001/002/000/012/002/uffe6/005" +
    "/uffe6/034/uffe6/043/uffe6/001/002/000/012/002/uffe5/005/uffe5" +
    "/034/uffe5/043/uffe5/001/002/000/020/002/ufff2/005/ufff2/025" +
    "/ufff2/045/ufff2/046/ufff2/047/ufff2/050/ufff2/001/002/000/020" +
    "/002/ufff0/005/ufff0/025/ufff0/045/ufff0/046/ufff0/047/ufff0/050" +
    "/ufff0/001/002/000/020/002/uffef/005/uffef/025/uffef/045/uffef" +
    "/046/uffef/047/uffef/050/uffef/001/002/000/020/002/ufff1/005" +
    "/ufff1/025/ufff1/045/ufff1/046/ufff1/047/ufff1/050/ufff1/001/002" +
    "/000/020/002/ufff4/005/ufff4/025/ufff4/045/ufff4/046/ufff4/047" +
    "/ufff4/050/ufff4/001/002/000/020/002/ufff5/005/ufff5/025/ufff5" +
    "/045/042/046/045/047/043/050/044/001/002/000/020/002" +
    "/ufff3/005/ufff3/025/ufff3/045/ufff3/046/ufff3/047/ufff3/050/ufff3" +
    "/001/002/000/010/002/ufffc/005/ufffc/016/ufffc/001/002/000" +
    "/010/002/ufffe/005/ufffe/016/ufffe/001/002/000/004/002/000" +
    "/001/002" });

  /** Access to parse-action table. */
  public override short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static readonly short[][] _reduce_table = 
    unpackFromStrings(new string[] {
    "/000/051/000/010/003/003/004/006/005/005/001/001/000" +
    "/002/001/001/000/004/006/051/001/001/000/006/010/010" +
    "/011/011/001/001/000/002/001/001/000/006/012/016/013" +
    "/015/001/001/000/004/007/012/001/001/000/002/001/001" +
    "/000/002/001/001/000/002/001/001/000/006/016/046/017" +
    "/045/001/001/000/002/001/001/000/006/014/017/015/021" +
    "/001/001/000/002/001/001/000/006/020/024/021/023/001" +
    "/001/000/002/001/001/000/006/022/035/023/036/001/001" +
    "/000/002/001/001/000/006/024/027/025/026/001/001/000" +
    "/006/026/031/027/032/001/001/000/002/001/001/000/002" +
    "/001/001/000/002/001/001/000/002/001/001/000/002/001" +
    "/001/000/002/001/001/000/002/001/001/000/002/001/001" +
    "/000/002/001/001/000/002/001/001/000/002/001/001/000" +
    "/002/001/001/000/002/001/001/000/002/001/001/000/002" +
    "/001/001/000/002/001/001/000/004/017/047/001/001/000" +
    "/002/001/001/000/002/001/001/000/002/001/001/000/002" +
    "/001/001" });

  /** Access to <code>reduce_goto</code> table. */
  public override short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP_ProgramParser_actions action_obj;

  /** Action encapsulation object initializer. */
  protected override void init_actions()
    {
      action_obj = new CUP_ProgramParser_actions(this);
    }

  /** Invoke a user supplied parse action. */
  public override TUVienna.CS_CUP.Runtime.Symbol do_action(
    int                        act_num,
    TUVienna.CS_CUP.Runtime.lr_parser parser,
    System.Collections.Stack            xstack1,
    int                        top)
  {
  mStack CUP_parser_stack= new mStack(xstack1);
    /* call code in generated class */
    return action_obj.CUP_ProgramParser_do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public override int start_state() {return 0;}
  /** Indicates start production. */
  public override int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public override int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public override int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
public class CUP_ProgramParser_actions {
  private ProgramParser my_parser;

  /** Constructor */
  public CUP_ProgramParser_actions(ProgramParser t_parser) {
    this.my_parser = t_parser;
  }

  /** Method with the actual generated action code. */
  public   TUVienna.CS_CUP.Runtime.Symbol CUP_ProgramParser_do_action(
    int                        CUP_ProgramParser_act_num,
    TUVienna.CS_CUP.Runtime.lr_parser CUP_ProgramParser_parser,
    System.Collections.Stack            xstack1,
    int                        CUP_ProgramParser_top)
    {
      /* Symbol object for return from actions */
      mStack CUP_ProgramParser_stack =new mStack(xstack1);
      TUVienna.CS_CUP.Runtime.Symbol CUP_ProgramParser_result;

      /* select the action based on the action number */
      switch (CUP_ProgramParser_act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ProgramEndOpt ::= ProgramEnd 
            {
              TypeCobol.Compiler.CodeElements.ProgramEnd RESULT = null;
		int peleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int peright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.ProgramEnd pe = (TypeCobol.Compiler.CodeElements.ProgramEnd)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = pe; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(5/*ProgramEndOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // ProgramEndOpt ::= 
            {
              TypeCobol.Compiler.CodeElements.ProgramEnd RESULT = null;

              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(5/*ProgramEndOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ioControlEntries ::= ioControlEntries IOControlEntry 
            {
              System.Collections.IList RESULT = null;
		int iocesleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int iocesright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		System.Collections.IList ioces = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int ioceleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int ioceright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.IOControlEntry ioce = (TypeCobol.Compiler.CodeElements.IOControlEntry)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = ioces; ioces.Add(ioce); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(21/*ioControlEntries*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ioControlEntries ::= IOControlEntry 
            {
              System.Collections.IList RESULT = null;
		int ioceleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int ioceright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.IOControlEntry ioce = (TypeCobol.Compiler.CodeElements.IOControlEntry)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new List<IOControlEntry>(); RESULT.Add(ioce); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(21/*ioControlEntries*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ioControlSentencesOpt ::= ioControlEntries SentenceEnd 
            {
              TypeCobol.DocumentModel.Dom.IoControlParagraph RESULT = null;
		int iocesleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int iocesright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		System.Collections.IList ioces = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int seleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int seright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.SentenceEnd se = (TypeCobol.Compiler.CodeElements.SentenceEnd)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
			RESULT = new IoControlParagraph(); 
			RESULT.IOControlEntries = (List<TypeCobol.Compiler.CodeElements.IOControlEntry>)ioces; 
			RESULT.SentenceEnd = se;
		
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(20/*ioControlSentencesOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ioControlSentencesOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.IoControlParagraph RESULT = null;
		 RESULT = new IoControlParagraph(); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(20/*ioControlSentencesOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ioControlParagraph ::= IOControlParagraphHeader ioControlSentencesOpt 
            {
              TypeCobol.DocumentModel.Dom.IoControlParagraph RESULT = null;
		int iocphleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int iocphright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.Compiler.CodeElements.IOControlParagraphHeader iocph = (TypeCobol.Compiler.CodeElements.IOControlParagraphHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int iocsleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int iocsright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.IoControlParagraph iocs = (TypeCobol.DocumentModel.Dom.IoControlParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = iocs; iocs.IOControlParagraphHeader = iocph; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(19/*ioControlParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ioControlParagraphOpt ::= ioControlParagraph 
            {
              TypeCobol.DocumentModel.Dom.IoControlParagraph RESULT = null;
		int iocpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int iocpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.IoControlParagraph iocp = (TypeCobol.DocumentModel.Dom.IoControlParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = iocp; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(18/*ioControlParagraphOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ioControlParagraphOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.IoControlParagraph RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(18/*ioControlParagraphOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // fileControlEntries ::= fileControlEntries FileControlEntry 
            {
              System.Collections.IList RESULT = null;
		int fcesleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int fcesright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		System.Collections.IList fces = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int fceleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int fceright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.FileControlEntry fce = (TypeCobol.Compiler.CodeElements.FileControlEntry)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = fces; fces.Add(fce); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(17/*fileControlEntries*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // fileControlEntries ::= FileControlEntry 
            {
              System.Collections.IList RESULT = null;
		int fceleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int fceright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.FileControlEntry fce = (TypeCobol.Compiler.CodeElements.FileControlEntry)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new List<FileControlEntry>(); RESULT.Add(fce); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(17/*fileControlEntries*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // fileControlEntriesOpt ::= fileControlEntries 
            {
              System.Collections.IList RESULT = null;
		int fcesleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int fcesright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		System.Collections.IList fces = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = fces; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(16/*fileControlEntriesOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // fileControlEntriesOpt ::= 
            {
              System.Collections.IList RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(16/*fileControlEntriesOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // fileControlParagraph ::= FileControlParagraphHeader fileControlEntriesOpt 
            {
              TypeCobol.DocumentModel.Dom.FileControlParagraph RESULT = null;
		int fcphleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int fcphright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.Compiler.CodeElements.FileControlParagraphHeader fcph = (TypeCobol.Compiler.CodeElements.FileControlParagraphHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int fcesleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int fcesright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		System.Collections.IList fces = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 
		RESULT = new FileControlParagraph(); 
		RESULT.FileControlParagraphHeader = fcph;
		RESULT.FileControlEntries = (List<TypeCobol.Compiler.CodeElements.FileControlEntry>)fces;
	
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(15/*fileControlParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // fileControlParagraphOpt ::= fileControlParagraph 
            {
              TypeCobol.DocumentModel.Dom.FileControlParagraph RESULT = null;
		int fcpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int fcpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.FileControlParagraph fcp = (TypeCobol.DocumentModel.Dom.FileControlParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = fcp; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(14/*fileControlParagraphOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // fileControlParagraphOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.FileControlParagraph RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(14/*fileControlParagraphOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // inputOutputSection ::= InputOutputSectionHeader fileControlParagraphOpt ioControlParagraphOpt 
            {
              TypeCobol.DocumentModel.Dom.InputOutputSection RESULT = null;
		int ioshleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left;
		int ioshright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).right;
		TypeCobol.Compiler.CodeElements.InputOutputSectionHeader iosh = (TypeCobol.Compiler.CodeElements.InputOutputSectionHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).value;
		int fcpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int fcpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.DocumentModel.Dom.FileControlParagraph fcp = (TypeCobol.DocumentModel.Dom.FileControlParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int iocpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int iocpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.IoControlParagraph iocp = (TypeCobol.DocumentModel.Dom.IoControlParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new InputOutputSection(iosh, fcp, iocp);  
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(11/*inputOutputSection*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // inputOutputSectionOpt ::= inputOutputSection 
            {
              TypeCobol.DocumentModel.Dom.InputOutputSection RESULT = null;
		int iosleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int iosright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.InputOutputSection ios = (TypeCobol.DocumentModel.Dom.InputOutputSection)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = ios; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(10/*inputOutputSectionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // inputOutputSectionOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.InputOutputSection RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(10/*inputOutputSectionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // configurationParagraph ::= RepositoryParagraph 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationParagraph RESULT = null;
		int rpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int rpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.RepositoryParagraph rp = (TypeCobol.Compiler.CodeElements.RepositoryParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationParagraph.Repository(rp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(13/*configurationParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // configurationParagraph ::= SpecialNamesParagraph 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationParagraph RESULT = null;
		int snpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int snpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.SpecialNamesParagraph snp = (TypeCobol.Compiler.CodeElements.SpecialNamesParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationParagraph.SpecialNames(snp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(13/*configurationParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // configurationParagraph ::= ObjectComputerParagraph 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationParagraph RESULT = null;
		int ocpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int ocpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.ObjectComputerParagraph ocp = (TypeCobol.Compiler.CodeElements.ObjectComputerParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationParagraph.ObjectComputer(ocp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(13/*configurationParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // configurationParagraph ::= SourceComputerParagraph 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationParagraph RESULT = null;
		int scpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int scpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.SourceComputerParagraph scp = (TypeCobol.Compiler.CodeElements.SourceComputerParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationParagraph.SourceComputer(scp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(13/*configurationParagraph*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // configurationParagraphs ::= configurationParagraphs configurationParagraph 
            {
              System.Collections.IList RESULT = null;
		int cpsleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int cpsright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		System.Collections.IList cps = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int cpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int cpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.ConfigurationParagraph cp = (TypeCobol.DocumentModel.Dom.ConfigurationParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = cps; cps.Add(cp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(12/*configurationParagraphs*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // configurationParagraphs ::= configurationParagraph 
            {
              System.Collections.IList RESULT = null;
		int cpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int cpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.ConfigurationParagraph cp = (TypeCobol.DocumentModel.Dom.ConfigurationParagraph)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new List<ConfigurationParagraph>(); RESULT.Add(cp); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(12/*configurationParagraphs*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // configurationSection ::= ConfigurationSectionHeader configurationParagraphs 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationSection RESULT = null;
		int cshleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int cshright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader csh = (TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int cpsleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int cpsright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		System.Collections.IList cps = (System.Collections.IList)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationSection(csh,(List<TypeCobol.DocumentModel.Dom.ConfigurationParagraph>)cps); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(9/*configurationSection*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // configurationSection ::= ConfigurationSectionHeader 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationSection RESULT = null;
		int cshleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int cshright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader csh = (TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ConfigurationSection(csh); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(9/*configurationSection*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // configurationSectionOpt ::= configurationSection 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationSection RESULT = null;
		int csleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int csright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.ConfigurationSection cs = (TypeCobol.DocumentModel.Dom.ConfigurationSection)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = cs; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(8/*configurationSectionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // configurationSectionOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.ConfigurationSection RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(8/*configurationSectionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // environmentDivision ::= EnvironmentDivisionHeader configurationSectionOpt inputOutputSectionOpt 
            {
              TypeCobol.DocumentModel.Dom.EnvironmentDivision RESULT = null;
		int edhleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left;
		int edhright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).right;
		TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader edh = (TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).value;
		int csleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int csright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.DocumentModel.Dom.ConfigurationSection cs = (TypeCobol.DocumentModel.Dom.ConfigurationSection)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int iocleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int iocright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.InputOutputSection ioc = (TypeCobol.DocumentModel.Dom.InputOutputSection)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new TypeCobol.DocumentModel.Dom.EnvironmentDivision(edh, cs, ioc); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(7/*environmentDivision*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // environmentDivisionOpt ::= environmentDivision 
            {
              TypeCobol.DocumentModel.Dom.EnvironmentDivision RESULT = null;
		int edleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int edright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.EnvironmentDivision ed = (TypeCobol.DocumentModel.Dom.EnvironmentDivision)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = ed; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(6/*environmentDivisionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // environmentDivisionOpt ::= 
            {
              TypeCobol.DocumentModel.Dom.EnvironmentDivision RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(6/*environmentDivisionOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LibraryCopyOpt ::= LibraryCopy 
            {
              TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement RESULT = null;
		int lcleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int lcright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement lc = (TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = lc; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(4/*LibraryCopyOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LibraryCopyOpt ::= 
            {
              TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement RESULT = null;
		 RESULT = null; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(4/*LibraryCopyOpt*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programAttributes ::= ProgramIdentification LibraryCopyOpt 
            {
              TypeCobol.DocumentModel.Dom.ProgramAttributes RESULT = null;
		int pidleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int pidright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.Compiler.CodeElements.ProgramIdentification pid = (TypeCobol.Compiler.CodeElements.ProgramIdentification)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int lcleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int lcright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement lc = (TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = new ProgramAttributes(pid, lc); 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(3/*programAttributes*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cobolProgram ::= programAttributes environmentDivisionOpt ProgramEndOpt 
            {
              TypeCobol.DocumentModel.Dom.CobolProgram RESULT = null;
		int pasleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left;
		int pasright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).right;
		TypeCobol.DocumentModel.Dom.ProgramAttributes pas = (TypeCobol.DocumentModel.Dom.ProgramAttributes)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).value;
		int edleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int edright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.DocumentModel.Dom.EnvironmentDivision ed = (TypeCobol.DocumentModel.Dom.EnvironmentDivision)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		int peleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int peright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.Compiler.CodeElements.ProgramEnd pe = (TypeCobol.Compiler.CodeElements.ProgramEnd)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 
		RESULT = new CobolProgram(); 
		RESULT.ProgramAttributes = pas;
		RESULT.EnvironmentDivision = ed;
		RESULT.ProgramEnd = pe;
	
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(2/*cobolProgram*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-2)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= cobolCompilationUnit EOF 
            {
              object RESULT = null;
		int start_valleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left;
		int start_valright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).right;
		TypeCobol.DocumentModel.Dom.CobolProgram start_val = (TypeCobol.DocumentModel.Dom.CobolProgram)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).value;
		RESULT = start_val;
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(0/*$START*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-1)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP_ProgramParser_parser.done_parsing();
          return CUP_ProgramParser_result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // cobolCompilationUnit ::= cobolProgram 
            {
              TypeCobol.DocumentModel.Dom.CobolProgram RESULT = null;
		int cpleft = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left;
		int cpright = ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right;
		TypeCobol.DocumentModel.Dom.CobolProgram cp = (TypeCobol.DocumentModel.Dom.CobolProgram)((TUVienna.CS_CUP.Runtime.Symbol) CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).value;
		 RESULT = cp; 
              CUP_ProgramParser_result = new TUVienna.CS_CUP.Runtime.Symbol(1/*cobolCompilationUnit*/, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).left, ((TUVienna.CS_CUP.Runtime.Symbol)CUP_ProgramParser_stack.elementAt(CUP_ProgramParser_top-0)).right, RESULT);
            }
          return CUP_ProgramParser_result;

          /* . . . . . .*/
          default:
            throw new System.Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

}
