using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TypeCobol.Compiler.CodeElements
{
    /// <summary>
    /// Interface for a Visitor on Code Elements only.
    /// </summary>
    /// <typeparam name="R"></typeparam>
    /// <typeparam name="D"></typeparam>
    public interface ICodeElementVisitor<R,D>
    {
        R Visit(TypeCobol.Compiler.CodeElements.DataDescriptionEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DataRedefinesEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DataRenamesEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DataConditionEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FileControlEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FileDescriptionEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.RerunIOControlEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SameAreaIOControlEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MultipleFileTapeIOControlEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ApplyWriteOnlyIOControlEntry that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DataDivisionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FileSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WorkingStorageSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.LocalStorageSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.LinkageSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DeclarativesEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DeclarativesHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FileControlParagraphHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FunctionDeclarationHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FunctionDeclarationEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InputOutputSectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.IOControlParagraphHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ParagraphHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ProcedureDivisionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SectionHeader that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SentenceEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.UseAfterIOExceptionStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.UseForDebuggingProcedureStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ClassEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ClassIdentification that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FactoryEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.FactoryIdentification that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MethodEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MethodIdentification that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ObjectEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ObjectIdentification that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ProgramEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ProgramIdentification that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ObjectComputerParagraph that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.RepositoryParagraph that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SourceComputerParagraph that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SpecialNamesParagraph that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AtEndCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AtEndOfPageCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InvalidKeyCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotAtEndCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotAtEndOfPageCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotInvalidKeyCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotOnExceptionCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotOnOverflowCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NotOnSizeErrorCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.OnExceptionCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.OnOverflowCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.OnSizeErrorCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AddStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.CallStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ComputeStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DeleteStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DivideStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.EvaluateStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InvokeStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MultiplyStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.PerformStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ReadStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ReturnStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.RewriteStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SearchStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.StartStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.StringStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SubtractStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.UnstringStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WriteStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.XmlStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AcceptFromInputDeviceStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AcceptFromSystemDateStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AddSimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AddGivingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AddCorrespondingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.AlterStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.CallStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ProcedureStyleCallStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.CancelStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.CloseStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ComputeStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ContinueStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DeleteStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DisplayStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DivideSimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DivideGivingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.DivideRemainderStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.EntryStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.EvaluateStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WhenCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WhenOtherCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ExecStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ExitMethodStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ExitProgramStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ExitStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.GobackStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.GotoSimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.GotoConditionalStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.IfStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ElseCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.NextSentenceStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.IfStatementEnd that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InitializeStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InspectTallyingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InspectConvertingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.InvokeStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MergeStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MoveSimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MoveCorrespondingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MultiplySimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.MultiplyGivingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.OpenStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.PerformStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ReadStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ReleaseStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.ReturnStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.RewriteStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SearchSerialStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SearchBinaryStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WhenSearchCondition that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SetStatementForAssignment that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SetStatementForIndexes that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SetStatementForSwitches that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SetStatementForConditions that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SortStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.StartStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.StopStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.StringStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SubtractSimpleStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SubtractGivingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.SubtractCorrespondingStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.UnstringStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.WriteStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.XmlGenerateStatement that, D data);
        R Visit(TypeCobol.Compiler.CodeElements.XmlParseStatement that, D data);
    }
}
